import type { Metadata } from 'next';
import { Laptop } from 'lucide-react';

import { AuctionSourceCard } from '@/components/auction-source-card';
import { AuctionShell } from '@/components/auction-shell';
import { federalAuctionSources, independentAuctionSources } from '@/lib/auction-data';

export const metadata: Metadata = { title: 'Online Public Vehicle Auctions', description: 'Official online public vehicle auction sources and clearly labeled independent auction-access options.', alternates: { canonical: '/public-auto-auctions/online' } };

export default function Page() { const online = federalAuctionSources.filter((source) => source.format !== 'in-person'); return <AuctionShell><main className="bg-[#dff4f8]"><section className="border-b-2 border-navy bg-navy px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-7xl"><Laptop className="size-10 text-teal-300" /><h1 className="mt-6 max-w-4xl text-5xl font-black uppercase leading-[.92] tracking-[-0.06em] sm:text-7xl">Online bidding starts off OwnerOnly.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Use this directory to reach verified official sources and separately labeled independent brokers. Registration, bidding, deposits, payments, and passwords stay with the operator.</p></div></section><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-[0.2em] text-teal-700">Government and official sources</p><h2 className="mt-3 text-4xl font-black uppercase text-navy">Official online starting points.</h2><div className="mt-8 grid gap-7 lg:grid-cols-2">{online.map((source) => <AuctionSourceCard key={source.id} source={source} />)}</div><div className="mt-14 border-t-[3px] border-navy pt-12"><p className="block-label">Independent third-party option</p><h2 className="mt-6 text-4xl font-black uppercase text-navy">Auction broker access.</h2><p className="mt-3 max-w-3xl leading-7 text-slate-700">Not a government source. Review membership, deposit, fee, binding-bid, title, payment, and pickup terms before registering.</p><div className="mt-8 grid gap-7 lg:grid-cols-2">{independentAuctionSources.map((source) => <AuctionSourceCard key={source.id} source={source} />)}</div></div></div></section></main></AuctionShell>; }
