import type { Metadata } from 'next';
import { ExternalLink, Laptop, LockKeyhole, ShieldCheck } from 'lucide-react';

import { AuctionShell } from '@/components/auction-shell';
import { federalAuctionSources } from '@/lib/auction-data';

export const metadata: Metadata = { title: 'Online Public Vehicle Auctions', description: 'Official online and hybrid public vehicle auction sources serving buyers across the United States.', alternates: { canonical: '/public-auto-auctions/online' } };

export default function Page() { const online = federalAuctionSources.filter((source) => source.format !== 'in-person'); return <AuctionShell><main className="bg-[#dff4f8]"><section className="border-b-2 border-navy bg-navy px-5 py-16 text-white sm:px-8"><div className="mx-auto max-w-7xl"><Laptop className="size-10 text-teal-300" /><h1 className="mt-6 max-w-4xl text-5xl font-black uppercase leading-[.92] tracking-[-0.06em] sm:text-7xl">Online bidding starts off OwnerOnly.</h1><p className="mt-6 max-w-3xl text-lg leading-8 text-slate-300">Use this directory to reach verified official sources. Registration, bidding, deposits, payments, and passwords stay with the auction operator.</p></div></section><section className="px-5 py-16 sm:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-5 lg:grid-cols-2">{online.map((source) => <article className="border-2 border-navy bg-white p-6 shadow-[6px_6px_0_rgba(7,28,44,.14)]" key={source.id}><div className="flex items-start justify-between gap-5"><div><p className="text-xs font-black uppercase tracking-wide text-teal-700">{source.format} · {source.category}</p><h2 className="mt-2 text-2xl font-black uppercase text-navy">{source.name}</h2></div>{source.publicAccess === 'confirmed' ? <ShieldCheck className="size-6 text-teal-700" /> : <LockKeyhole className="size-6 text-amber-700" />}</div><p className="mt-4 text-sm leading-6 text-slate-600">{source.publicAccessNote}</p><p className="mt-5 border-t border-slate-200 pt-4 text-xs font-bold text-slate-500">Last verified {source.lastChecked} · Review the live operator terms before registering.</p><a className="mt-5 inline-flex items-center gap-2 bg-navy px-4 py-3 text-xs font-black uppercase text-white" href={source.officialUrl} rel="noopener noreferrer" target="_blank">Open official operator <ExternalLink className="size-4" /></a></article>)}</div></div></section></main></AuctionShell>; }
