import { CheckCircle2, LockKeyhole } from 'lucide-react';

import { SiteHeader } from '@/components/site-header';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

export function AuthPage({ mode }: { mode: 'login' | 'signup' }) {
  const signup = mode === 'signup';
  return (
    <><SiteHeader /><main className="grid min-h-[calc(100vh-5rem)] bg-[#f8f4e9] lg:grid-cols-2"><section className="flex items-center px-5 py-14 sm:px-10 lg:px-[max(3rem,calc((100vw-80rem)/2))]"><div className="w-full max-w-md"><p className="text-xs font-black uppercase tracking-[0.23em] text-teal-700">{signup ? 'Join the marketplace' : 'Welcome back'}</p><h1 className="mt-3 text-4xl font-black uppercase tracking-[-0.05em] text-navy">{signup ? 'Create your account.' : 'Log in securely.'}</h1><p className="mt-3 text-slate-600">{signup ? 'Browse immediately. Verify before listing or messaging.' : 'Access favorites, messages, listings, and verification status.'}</p><form className="mt-8 space-y-5 border-2 border-navy bg-white p-6 shadow-[8px_8px_0_#071c2c]"><label className="block text-sm font-bold text-navy">Email address<Input className="mt-2 h-11 rounded-none" type="email" placeholder="you@example.com" /></label>{signup && <label className="block text-sm font-bold text-navy">Mobile phone<Input className="mt-2 h-11 rounded-none" type="tel" placeholder="(555) 555-1234" /></label>}<label className="block text-sm font-bold text-navy">Password<Input className="mt-2 h-11 rounded-none" type="password" placeholder="At least 12 characters" /></label><Button className="h-12 w-full rounded-none bg-teal-500 font-black uppercase text-navy hover:bg-teal-400">{signup ? 'Create account' : 'Log in'}</Button><p className="text-center text-xs text-slate-500">Demo form—authentication is not connected in this prototype.</p></form><p className="mt-6 text-sm text-slate-600">{signup ? 'Already have an account?' : 'New to OwnerOnly?'} <a className="font-bold text-teal-800 underline" href={signup ? '/login' : '/signup'}>{signup ? 'Log in' : 'Create an account'}</a></p></div></section><section className="hidden items-center bg-navy px-16 text-white lg:flex"><div className="max-w-lg"><LockKeyhole className="size-12 text-teal-300" /><h2 className="mt-6 text-4xl font-black uppercase leading-none tracking-[-0.05em]">Verify once. Know what every badge means.</h2><ul className="mt-8 space-y-5 text-slate-300">{['Phone and account confirmation', 'Hosted ID + selfie check', 'Separate ownership-document review', 'Approximate public location only'].map((item) => <li className="flex items-center gap-3" key={item}><CheckCircle2 className="size-5 text-teal-300" />{item}</li>)}</ul></div></section></main></>
  );
}
