'use client';

import { useState } from 'react';
import { ArrowLeft, ArrowRight, Camera, CheckCircle2, FileCheck2, ShieldCheck } from 'lucide-react';

import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { CARFAX_REPORTS_URL, validateSellerCarfaxUrl } from '@/lib/carfax';

const steps = ['VIN & vehicle', 'Price & condition', 'Features & story', 'Photos', 'Ownership', 'Review'];

export function ListingWizard() {
  const [step, setStep] = useState(0);
  const [carfaxUrl, setCarfaxUrl] = useState('');
  const carfaxValidation = validateSellerCarfaxUrl(carfaxUrl);
  return (
    <div>
      <div className="grid grid-cols-3 border-2 border-navy bg-white sm:grid-cols-6">{steps.map((label, index) => <button className={`border-navy p-3 text-left text-xs font-black uppercase tracking-wide sm:min-h-20 ${index > 0 ? 'border-l' : ''} ${step === index ? 'bg-teal-400 text-navy' : index < step ? 'bg-teal-50 text-teal-800' : 'text-slate-500'}`} key={label} onClick={() => setStep(index)} type="button"><span className="block text-[10px]">{String(index + 1).padStart(2, '0')}</span><span className="mt-1 block">{label}</span></button>)}</div>
      <section className="mt-7 border-2 border-navy bg-white p-6 shadow-[8px_8px_0_rgba(7,28,44,.15)] sm:p-8">
        <p className="text-xs font-black uppercase tracking-[0.2em] text-teal-700">Step {step + 1} of 6</p>
        {step === 0 && <div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight text-navy">Start with the VIN.</h2><p className="mt-2 text-slate-600">NHTSA vPIC will decode basic vehicle information. You can correct non-authoritative descriptive fields later.</p><label className="mt-7 block max-w-lg text-sm font-bold text-navy">17-character VIN<Input className="mt-2 h-12 rounded-none font-mono uppercase" defaultValue="1A2BC3DE4FG567890" maxLength={17} /></label><div className="mt-5 border-l-4 border-teal-500 bg-teal-50 p-4 text-sm text-slate-700"><ShieldCheck className="mr-2 inline size-4" />Demo decoder response: 2021 · crossover · gasoline · automatic</div></div>}
        {step === 1 && <div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight text-navy">Set the facts and price.</h2><div className="mt-7 grid gap-5 sm:grid-cols-2"><Field label="Mileage" value="38240" /><Field label="Asking price" value="24800" /><SelectField label="Condition" value="Good" /><SelectField label="Title status" value="Clean" /><SelectField label="Lien status" value="No lien" /></div></div>}
        {step === 2 && <div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight text-navy">Tell the owner’s story.</h2><div className="mt-7 grid gap-5 sm:grid-cols-2"><SelectField label="Drivetrain" value="AWD" /><SelectField label="Fuel type" value="Gasoline" /><SelectField label="Transmission" value="Automatic" /></div><label className="mt-5 block text-sm font-bold text-navy">Seller description<Textarea className="mt-2 min-h-36 rounded-none" defaultValue="Well-kept everyday vehicle with regular maintenance. Selling because our household needs changed." /></label><div className="mt-7 border-2 border-navy bg-teal-50 p-5"><p className="text-xs font-black uppercase tracking-[0.18em] text-teal-800">Vehicle history · optional</p><label className="mt-3 block text-sm font-bold text-navy" htmlFor="carfax-url">CARFAX report link</label><Input aria-describedby="carfax-help carfax-error" aria-invalid={!carfaxValidation.valid} className="mt-2 h-12 rounded-none bg-white" id="carfax-url" inputMode="url" onChange={(event) => setCarfaxUrl(event.target.value)} placeholder="https://www.carfax.com/..." type="url" value={carfaxUrl} /><p className="mt-2 text-sm leading-6 text-slate-600" id="carfax-help">Paste the official share link hosted on carfax.com. Do not upload a PDF or screenshot. Buyers will be told to confirm that the report VIN matches the vehicle.</p>{!carfaxValidation.valid && <p className="mt-2 text-sm font-bold text-red-700" id="carfax-error">{carfaxValidation.message}</p>}<a className="mt-3 inline-block text-sm font-black text-teal-800 underline" href={CARFAX_REPORTS_URL} rel="noreferrer" target="_blank">Get a report directly from CARFAX</a><p className="mt-2 text-xs text-slate-500">This is a direct, non-affiliate link. CARFAX is not an OwnerOnly verification badge.</p></div></div>}
        {step === 3 && <div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight text-navy">Add clear, current photos.</h2><p className="mt-2 text-slate-600">Production uploads validate signature, type, file size, dimensions, quantity, and remove metadata server-side.</p><button className="mt-7 flex min-h-56 w-full flex-col items-center justify-center border-2 border-dashed border-slate-400 bg-slate-50 p-8 text-center" type="button"><Camera className="size-10 text-teal-700" /><span className="mt-4 font-black uppercase text-navy">Choose vehicle photos</span><span className="mt-2 text-sm text-slate-500">JPG, PNG or WebP · demo control</span></button></div>}
        {step === 4 && <div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight text-navy">Submit ownership proof.</h2><p className="mt-2 max-w-2xl leading-7 text-slate-600">Upload a current title or registration to a private, access-controlled bucket. Review compares only the verified legal name and VIN. Documents are automatically removed after a configurable retention period.</p><button className="mt-7 flex min-h-48 w-full max-w-xl flex-col items-center justify-center border-2 border-dashed border-slate-400 bg-slate-50 p-8 text-center" type="button"><FileCheck2 className="size-10 text-teal-700" /><span className="mt-4 font-black uppercase text-navy">Choose private document</span><span className="mt-2 text-sm text-slate-500">Not stored in this demonstration</span></button></div>}
        {step === 5 && <div><h2 className="mt-3 text-3xl font-black uppercase tracking-tight text-navy">Review before submission.</h2><div className="mt-7 grid gap-4 sm:grid-cols-2">{['VIN decoded', 'Vehicle facts entered', 'Description complete', carfaxUrl.trim() ? carfaxValidation.valid ? 'CARFAX link added (seller-provided)' : 'CARFAX link needs correction' : 'CARFAX link not added (optional)', 'Photos still needed', 'Ownership document still needed', 'Seller attestation required'].map((item, index) => { const ready = index < 3 || index === 3 && carfaxValidation.valid; return <div className={`flex gap-3 border p-4 ${ready ? 'border-teal-500 bg-teal-50' : 'border-amber-400 bg-amber-50'}`} key={item}><CheckCircle2 className={`size-5 ${ready ? 'text-teal-700' : 'text-amber-700'}`} /><span className="text-sm font-bold text-navy">{item}</span></div>; })}</div><label className="mt-7 flex items-start gap-3 text-sm leading-6 text-slate-700"><input className="mt-1 size-4" type="checkbox" />I attest that I own this vehicle, am not acting as a dealer, broker, reseller, or representative, and the listing is accurate to the best of my knowledge.</label><Button className="mt-6 h-12 rounded-none bg-slate-300 font-black uppercase text-slate-600" disabled>Submit for review</Button></div>}
        <div className="mt-10 flex justify-between border-t border-slate-200 pt-6"><Button className="rounded-none" disabled={step === 0} onClick={() => setStep((current) => Math.max(0, current - 1))} variant="outline"><ArrowLeft /> Back</Button>{step < 5 && <Button className="rounded-none bg-navy" onClick={() => setStep((current) => Math.min(5, current + 1))}>Save & continue <ArrowRight /></Button>}</div>
      </section>
    </div>
  );
}

function Field({ label, value }: { label: string; value: string }) { return <label className="text-sm font-bold text-navy">{label}<Input className="mt-2 h-11 rounded-none" defaultValue={value} /></label>; }
function SelectField({ label, value }: { label: string; value: string }) { return <label className="text-sm font-bold text-navy">{label}<select className="mt-2 h-11 w-full border border-slate-300 bg-white px-3 text-sm" defaultValue={value}><option>{value}</option><option>Other</option></select></label>; }
