import type { Metadata } from 'next';
import { AlertCircle, ArrowRight, CalendarClock, CheckCircle2, ExternalLink, FileWarning, Flag, MapPinned, ShieldQuestion } from 'lucide-react';

import { AuctionShell } from '@/components/auction-shell';
import { AuctionSourceCard } from '@/components/auction-source-card';
import { auctionCategories, federalAuctionSources, findStateGuide, stateAuctionGuides } from '@/lib/auction-data';

export function generateStaticParams() { return stateAuctionGuides.map((state) => ({ state: state.slug })); }

export function generateMetadata({ params }: { params: { state: string } }): Metadata {
  const state = findStateGuide(params.state);
  if (!state) return { title: 'State Auction Guide Not Found' };
  return { title: `${state.name} Public Auto Auctions`, description: `Official-source guide to public government, surplus, seized, police, impound, and online vehicle auctions serving ${state.name}.`, alternates: { canonical: `/public-auto-auctions/${state.slug}` } };
}

export default function Page({ params }: { params: { state: string } }) {
  const state = findStateGuide(params.state);
  if (!state) return <AuctionShell><main className="bg-[#f8f4e9] px-5 py-24 text-center"><h1 className="text-4xl font-black uppercase text-navy">State guide not found.</h1><a className="mt-6 inline-flex items-center gap-2 font-black uppercase text-teal-800" href="/public-auto-auctions">View all states <ArrowRight /></a></main></AuctionShell>;
  const structuredData = { '@context': 'https://schema.org', '@type': 'CollectionPage', name: `${state.name} Public Auto Auctions`, description: `Independent official-source vehicle auction guide for ${state.name}.`, about: { '@type': 'State', name: state.name } };
  return (
    <AuctionShell>
      <main className="bg-[#f8f4e9]">
        <script dangerouslySetInnerHTML={{ __html: JSON.stringify(structuredData) }} type="application/ld+json" />
        <section className="border-b-2 border-navy bg-[#96d9ed] px-5 py-14 sm:px-8">
          <div className="mx-auto max-w-7xl"><nav aria-label="Breadcrumb" className="text-xs font-bold uppercase tracking-wide text-navy/65"><a href="/public-auto-auctions">Public Auto Auctions</a> / {state.name}</nav><div className="mt-6 grid gap-8 lg:grid-cols-[1fr_260px] lg:items-end"><div><p className="text-xs font-black uppercase tracking-[0.23em] text-teal-800">{state.code} · {state.region} region</p><h1 className="mt-3 text-5xl font-black uppercase leading-[.9] tracking-[-0.065em] text-navy sm:text-7xl">{state.name} public auto auctions.</h1><p className="mt-5 max-w-3xl text-lg leading-8 text-navy/75">A state-focused directory for official government surplus, seized, police, sheriff, impound, and online vehicle auction sources—kept separate from private-owner cars.</p></div><div className="border-2 border-navy bg-white p-5 shadow-[6px_6px_0_#071c2c]"><MapPinned className="size-7 text-teal-700" /><p className="mt-4 text-xs font-black uppercase tracking-wide text-slate-500">Map location</p><p className="mt-1 text-xl font-black uppercase text-navy">U.S. {state.region}</p><a className="mt-4 inline-flex items-center gap-2 text-xs font-black uppercase text-teal-800 underline" href={state.officialDirectoryUrl} rel="noopener noreferrer" target="_blank">Official state directory <ExternalLink className="size-3" /></a></div></div></div>
        </section>

        <section className="px-5 py-14 sm:px-8"><div className="mx-auto max-w-7xl"><div className="grid gap-6 lg:grid-cols-[1fr_340px]"><div><div className="flex items-end justify-between border-b-2 border-navy pb-4"><div><p className="text-xs font-black uppercase tracking-wide text-teal-700">Current verified events</p><h2 className="mt-2 text-3xl font-black uppercase text-navy">No active schedule confirmed.</h2></div><CalendarClock className="size-7 text-slate-500" /></div><div className="mt-5 border-2 border-dashed border-slate-400 bg-white p-7"><p className="leading-7 text-slate-700">OwnerOnly has not published a currently verified {state.name} vehicle-auction event. Event dates, closing times, fees, deposits, payment methods, inspection dates, inventory, title details, and pickup rules will appear only after confirmation from an official source.</p><p className="mt-4 text-sm font-black uppercase text-amber-800">Not confirmed—check with the auction.</p></div></div><aside className="border-2 border-navy bg-[#f6b82b] p-6 shadow-[6px_6px_0_rgba(7,28,44,.16)]"><ShieldQuestion className="size-7" /><h2 className="mt-4 text-2xl font-black uppercase text-navy">Registration checklist</h2><ul className="mt-5 space-y-3 text-sm leading-6 text-navy/80"><li>• General-public eligibility: not confirmed for state/local events.</li><li>• Dealer, salvage or dismantler license: check each lot.</li><li>• Buyer premium and deposit: not confirmed.</li><li>• Payment and pickup: operator terms control.</li><li>• Inspection and title information: confirm before bidding.</li></ul></aside></div></div></section>

        <section className="border-y-2 border-navy bg-[#dff4f8] px-5 py-14 sm:px-8"><div className="mx-auto max-w-7xl"><p className="text-xs font-black uppercase tracking-wide text-teal-700">State and local source coverage</p><h2 className="mt-3 text-4xl font-black uppercase tracking-[-0.05em] text-navy">Verification queue for {state.name}.</h2><div className="mt-8 grid gap-4 md:grid-cols-2 xl:grid-cols-5">{auctionCategories.map((category, index) => <article className="border-2 border-navy bg-white p-5" key={category}><span className="text-xs font-black tracking-widest text-teal-700">{String(index + 1).padStart(2, '0')}</span><h3 className="mt-5 font-black uppercase leading-tight text-navy">{category}</h3><p className="mt-4 text-xs leading-5 text-slate-600">No source published until official agency ownership or contractor authorization is confirmed by a human reviewer.</p><p className="mt-4 flex items-center gap-2 text-xs font-black uppercase text-amber-800"><AlertCircle className="size-4" /> Review needed</p></article>)}</div><a className="mt-7 inline-flex items-center gap-2 border border-navy bg-white px-4 py-3 text-xs font-black uppercase text-navy" href={state.officialDirectoryUrl} rel="noopener noreferrer" target="_blank">Find official {state.name} agencies <ExternalLink className="size-3" /></a></div></section>

        <section className="px-5 py-14 sm:px-8"><div className="mx-auto max-w-7xl"><div className="flex items-end justify-between border-b-2 border-navy pb-4"><div><p className="text-xs font-black uppercase tracking-wide text-teal-700">Online sources serving {state.code}</p><h2 className="mt-2 text-3xl font-black uppercase text-navy">Verified federal starting points.</h2></div><CheckCircle2 className="size-7 text-teal-700" /></div><div className="mt-7 grid gap-7 lg:grid-cols-3">{federalAuctionSources.slice(1, 4).map((source) => <AuctionSourceCard key={source.id} source={source} />)}</div></div></section>

        <section className="border-t-2 border-navy bg-navy px-5 py-12 text-white sm:px-8"><div className="mx-auto flex max-w-7xl flex-col gap-6 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><FileWarning className="mt-1 size-6 shrink-0 text-[#f6b82b]" /><div><h2 className="font-black uppercase">See something outdated?</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-300">Report a broken link, changed access rule, expired event, or incorrect source. New information stays unpublished until human review.</p></div></div><a className="inline-flex shrink-0 items-center gap-2 bg-white px-5 py-3 text-xs font-black uppercase text-navy" href="/help#report-auction-info"><Flag className="size-4" /> Report outdated info</a></div></section>
      </main>
    </AuctionShell>
  );
}
